### ISSUE TITLE
Character entity reference

### ISSUE THREAD

**Issue by jim-rosales** [santiagobs/colmaracademy#2]
If you take a look below, currently the ampersand symbol is highlighted in red. The reason for this is that the symbol is a reserved a character in HTML that is used to add special characters via their [entity reference](https://developer.mozilla.org/en-US/docs/Glossary/Entity).  

Considering this all you need to fix this issue is replace `&` with `&amp;`

https://github.com/santiagobs/colmaracademy/blob/3fc5e97cd78bc1ccbf60ec956562dd81c6b3280f/index.html#L56

**Comment by santiagobs** [comment]
I had no idea about those reserved characters, but it makes perfect sense. I'll include that entity reference documentation in my notes, thank you!
