### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by jim-rosales** [santiagobs/colmaracademy#3]
Consider reading through this [style guide](https://github.com/airbnb/css) and adopting some of its guidelines. This will improve the readability of your CSS file. 

For example one of the guidelines specified is having one selector per line:
```CSS
.one,
.selector,
.per-line {

}
```

https://github.com/santiagobs/colmaracademy/blob/3fc5e97cd78bc1ccbf60ec956562dd81c6b3280f/resources/css/style.css#L7-L12

**Comment by santiagobs** [comment]
Will do, thank you!
