### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [santiagobs/colmaracademy#5]
Grade: Exceeds Expectations

Summary:
Santiago, fantastic job on your capstone project! Your visual additions to the project like the hover effects and color scheme added a unique twist to the project and went above and beyond the project specifications! Apart from this syntactically you did a flawless job with only one small issue that should be a quick fix.  

To practice a bit more considering researching [variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables). They are a great tool that will allow you to both improve the maintainability of your project and its readability!

**Comment by santiagobs** [comment]
Thank you! Variables seem very interesting, I will definitely use them.
